<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CustomerServiceCampaign.Modules.Users.Presentation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\CustomerServiceCampaign.Common.Infrastructure\CustomerServiceCampaign.Common.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Common\CustomerServiceCampaign.Common.Presentation\CustomerServiceCampaign.Common.Presentation.csproj" />
    <ProjectReference Include="..\CustomerServiceCampaign.Modules.Users.Application\CustomerServiceCampaign.Modules.Users.Application.csproj" />
  </ItemGroup>

</Project>
