<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>d5c8ecce-dfea-4cb0-b39f-67680938bc5b</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\CustomerServiceCampaign.Api\CustomerServiceCampaign.Api.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Scalar.AspNetCore" Version="2.11.10" />
    </ItemGroup>

</Project>
