<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CustomerServiceCampaign.Common.Presentation</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CustomerServiceCampaign.Common.Domain\CustomerServiceCampaign.Common.Domain.csproj" />
  </ItemGroup>

</Project>
