<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>CustomerServiceCampaign.Common.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" Version="9.0.0" />
    <PackageReference Include="AspNetCore.HealthChecks.Uris" Version="9.0.0" />
    <PackageReference Include="MassTransit" Version="8.2.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.2.1" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.11" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="EFCore.NamingConventions" Version="9.0.0" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.14.0" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.14.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.14.0" />
    <PackageReference Include="OpenTelemetry.Instrumentation.EntityFrameworkCore" Version="1.0.0-beta.11" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.14.0" />
    <PackageReference Include="Quartz.Extensions.Hosting" Version="3.8.1" />
    <PackageReference Include="Scrutor" Version="4.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CustomerServiceCampaign.Common.Application\CustomerServiceCampaign.Common.Application.csproj" />
  </ItemGroup>

</Project>
